apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1UQXhNekl3TlRrMU1Wb1hEVE15TVRBeE1ESXhNRFExTVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFNiCjRHNlhDcDZ0eFdaTkE0c0RmTHhRVTRaWXNsZlBIR2hiMEtnN3czeStKV1dGLzBPMVdTR2VJZmZiTE96TW56MVQKY1lOZnFrc2xVZFRGTm5nOHNOZldoWmgvNUJPQlFnQzg1MmNhcFY0b3hSR1BUSzg4bkEwSmFzUkowQWJ0S3QzVAo4MzFuTXoybUxZdkxqUXNJRCtOajFRNXVXQkNoZDJlM1A2WVJaVjZwZVJXNkdyTG1pL3d0RXFyRmtWanlBbGtGCmtpTnEzUkwrVFY1ZElOT0lSRXFEcDZzM1FzYy92YUlRTTdNYVNUTWUvbGMrVkpad244ZllnN1NpTWFiWTFCcWcKSkh6UnNETTV5OUN1alBuV09PaUIwMm05bXZWS3N0UVY5Ymd6S2hNNWpTa1poQ0thTE1LUjRlSENocHhpMmJWQQoxK2orOHlZQ21TQWcvQTJhRnlzQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGQVFpVUZTZXlRWEJLR0lDdkowMU9ZTkdrendiTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQWpLd2FJek4vWm5IK3ZVVmE4UG9EeU02TzBycC9vNVlwQ1MzN0NDRmhCdFFUcQpMWFAwdDlVZGQ2eHhuNGpMdldGMzFCbDNUN1ZCYUNuMlE1eXNUYTJTZVE2enBaK1B1S2pYV3puVG01R0krR2VnCkhoMHEvWHhqd2JtNEV6VzlicGo2bmpYdWxFYUxqT2dzRVdqQSttZUNhVlBLdHlTamFpd0tpQ3RTR1MwbVN5Q0UKekxCVmRYT21uN00rcjZWRmdYWmtiQ0JjUjN2UmRMblhaZVlrTDZIbjFmTjR6bzU4RVJwMmYrU2ptTDcxYzFFdAovSURlbjdINlNNOEl5RzVVT1kxTkd4WTFvMXpsY0UyeUZZUTc1NGRpbHVFT292TDdjZU5wR3NGRk5WSHdJM1YxCis2d1pyTW0xMkNIdTlHK29rVlZldkdnbFpua1NXRjNBMWY4L2pyWHYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://210.109.63.11:6443
  name: petclinic-msa
contexts:
- context:
    cluster: petclinic-msa
    user: petclinic-msa-admin
  name: petclinic-msa-admin@petclinic-msa
current-context: petclinic-msa-admin@petclinic-msa
kind: Config
preferences: {}
users:
- name: petclinic-msa-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: kic-iam-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://iam.kakaoi.io/identity/v3"
      - name: "OS_AUTH_TYPE"
        value: "v3applicationcredential"
      - name: "OS_APPLICATION_CREDENTIAL_ID"
        value: "{7526243abdae4e079d79ff2493e239ad}"
      - name: "OS_APPLICATION_CREDENTIAL_SECRET"
        value: "{u-1MryGQpSFugQJzFhHv3DilfH1ksUERaX54jXEGh4E1a1DjW8AtMSncGGPyGVOB1qPrkuQBUp6hGeprgA2RvQ}"
      - name: "OS_REGION_NAME"
        value: "kr-central-1"
      provideClusterInfo: false
